### PR TITLE
fix: Mounting Revolt.toml in compose.yml

### PR DESCRIPTION
**Pull request by ReStranger**
## Please make sure to check the following tasks before opening and submitting a PR
Co-authored-by: @loss-and-quick

- [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/.github/blob/master/.github/CONTRIBUTING.md)
- [x] I have tested my changes locally and they are working as intended

### CODE REVIEW

**Comment by loss-and-quick** [comment]
> Is there an issue with the one-line bind mount?

Yes, file mounts as folder path, not as file

**Comment by Mateleo** [comment]
@loss-and-quick I'm pretty sure it's not, the default config is working for me:
- /apps/revolt/Revolt.toml:/Revolt.toml

**Comment by loss-and-quick** [comment]
> @loss-and-quick I'm pretty sure it's not, the default config is working for me:
> 
> * /apps/revolt/Revolt.toml:/Revolt.toml

🤔🤔

**Comment by insertish** [comment]
Okay it does seem to do a check if the source exists, which is better than not having it I suppose.
Cherry picking the change since there are other services to be included now.

**Comment by ReStranger** [comment]
Good cherry pick [chore: switch to bind mount format](https://github.com/revoltchat/self-hosted/commit/0bc2c6548bbb129775b530bf440effe168cc93c4). Why don't you cite authorship?

**Pull request closed without merging**
