### PR TITLE
Added Voice Server (Vortex/Voso)

### PR DESCRIPTION
**Pull request by tuxsudo12**
Added voso to the docker-compose with needed configuration options

### CODE REVIEW

**Comment by tuxsudo12** [comment]
Also recommend adding https://github.com/revoltchat/self-hosted/pull/21 along with this one

**Comment by insertish** [comment]
The only thing blocking these issues is that Vortex is still in heavy development and would probably cause more headache bundling it in here than not. I would rather wait until development on it is stable rather than add it now.

**Comment by insertish** [comment]
Not going to merge since I do not recommend anybody run version 2 of the voice server, it barely works in production currently.

Waiting until rewrite is complete.

**Comment by DrMxrcy** [comment]
Is Vortex Still not ready to be used in the self hosted stack?

**Comment by insertish** [comment]
No, development on Vortex is paused until I finish the new web client.

**Comment by FiveMDevv** [comment]
> No, development on Vortex is paused until I finish the new web client.

Is there any update on Vortex?

**Comment by Rexogamer** [comment]
Insert's reply is still the case.

**Pull request closed without merging**
