### PR TITLE
add vortex voice server

### PR DESCRIPTION
**Pull request by blukai**
I was wondering...
What was the reason for not including voice server by default?

This resolves https://github.com/revoltchat/self-hosted/issues/105.

### CODE REVIEW

**Comment by DeclanChidlow** [comment]
Vortex is old, a tad busted, and unsupported. A new voice server is in development and, as such, trying to get Vortex hosted isn't something we intend to support or provide official guidance on.

**Comment by blukai** [comment]
> Vortex is old, a tad busted, and unsupported.

well, it works, it's functional.

pardon my curiosity:

> A new voice server is in developmen

last commit on the [rewrite branch](https://github.com/revoltchat/vortex/tree/vortex) is 2 years ago. is the new rewrite happening somewhere else?

> trying to get Vortex hosted isn't something we intend to support or provide official guidance on.

does app.revolt.chat rely something else for voice chat?

**Comment by DeclanChidlow** [comment]
Work is ongoing here:
https://github.com/revoltchat/backend/pull/318

The current production deployment at app.revolt.chat 'relies' on Vortex, but it frequently fails and is largely considered non-viable without significant fiddling. Most users can't use it and we conciser it completely unsupported.

**Comment by blukai** [comment]
got it, thanks for the info!

**Pull request closed without merging**
